### ISSUE TITLE
Website volumes: Changes on the host doesn't apply in docker

### ISSUE THREAD

**Issue by erwagasore** [nickjj/deploy-web-apps-with-docker#1]
Hello, I just 've bought the book but I am experiencing an issue with volumes changes.
As you mentioned in the book Changing "Hello, World" to something else doesn't change until I kill and restart the containers.

I am using Mac OS 10.10 and I have installed Docker Toolbox

**Comment by nickjj** [comment]
Hi @erwagasore,

Thanks for investing in the book. Can you please paste the contents of your `docker-compose.yml` file. Feel free to omit anything sensitive like passwords.

**Comment by erwagasore** [comment]
```
cadvisor:
  image: google/cadvisor:latest
  volumes:
    - '/:rootfs:ro'
    - '/var/run:/var/run:rw'
    - '/sys:/sys:ro'
    - '/var/lib/docker/:/var/lib/docker:ro'
  ports:
    - '8080:8080'  

redis:
  image: redis:latest
  ports:
    - '6379:6379'
  volumes:
    - './redis/data:/var/lib/redis/data'

app:
  build: .
  command: flask run -h 0.0.0.0 -p 3000
  links:
    - redis
  volumes:
    - '.:/rediscounter'
  ports:
    - '3000:3000'
  env_file:
    - .env
```
